project_id = "xnyfckmyvhrikikhzdvy"

[functions.ai-chat]
verify_jwt = false

[functions.generate-document]
verify_jwt = false

[functions.analyze-pdf]
verify_jwt = false

[functions.legal-articles]
verify_jwt = false

[functions.dual-domain-reasoning]
verify_jwt = false

[functions.emergency-guidance]
verify_jwt = false

[functions.predict-risks]
verify_jwt = false

[functions.corpus-ingestion]
verify_jwt = false

[functions.corpus-search]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.scrape-india-code]
verify_jwt = false

[functions.fetch-nha-documents]
verify_jwt = false

[functions.fetch-indian-kanoon]
verify_jwt = false

[functions.update-legal-content]
verify_jwt = false