project_id = "xnyfckmyvhrikikhzdvy"

[functions.ai-chat]
verify_jwt = false

[functions.generate-document]
verify_jwt = false

[functions.analyze-pdf]
verify_jwt = false

[functions.legal-articles]
verify_jwt = false