// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnyfckmyvhrikikhzdvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhueWZja215dmhyaWtpa2h6ZHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDIwMjEsImV4cCI6MjA3MDgxODAyMX0.STJ7335PoE7q62eZeiScxVj94o8tzqggjsGwQfY7owg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});